services:

  api:
    build: ./api
    image: ancientelfz/api:6.0
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
      - /app/node_modules
    environment:
       DATABASE_URL: ${DATABASE_URL}
  frontend:
    build: ./frontend
    image: ancientelfz/frontend:6.0
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules