name: Docs Main

on:
  push:
    branches: [main]
    paths:
      - "api/**"
      - ".github/workflows/docs-main.yml"
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [main]

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Docs
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false
          lfs: false

      # 1) Generera swagger till api/docs
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: api/package-lock.json

      - name: Install (api)
        working-directory: api
        run: npm ci --include=dev

      - name: Generate API docs
        working-directory: api
        run: npm run docs:gen # skapar api/docs/index.html + swagger.json

      # 2) Deploy statiska docs-mappen till SWA
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_VICTORIOUS_ROCK_0B9FCA903 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "./api/docs" # peka direkt på genererade filer
          api_location: "" # ingen Functions-API
          output_location: "" # ingen build-output

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_VICTORIOUS_ROCK_0B9FCA903 }}
          action: "close"
