name: CI

on:
  push:
    branches: [main]
    paths:
      - "frontend/**"
      - "api/**"
      - "db/**"

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install
        run: npm ci

      # - name: Test
      #   run: npm test -- --ci --watchAll=false --passWithNoTests

      - name: Build
        run: npm run build --if-present

  api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: api/package-lock.json

      - name: Install
        run: npm ci

      - name: Test
        run: npm test

      - name: Build
        run: npm run build --if-present

  db:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: db
    steps:
      - uses: actions/checkout@v4
      - name: Show files
        run: |
          pwd
          ls -la
          test -f init.sql && echo "init.sql found ✅" || (echo "init.sql missing ❌" && exit 1)
