name: SWA Staging (develop)

on:
  push:
    branches: [ develop ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ develop ]

jobs:
  deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Build & Deploy to SWA (staging)
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_POLITE_TREE_060449F03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: ./frontend
          api_location: ""
          output_location: dist

  close_pr:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: Azure/static-web-apps-deploy@v1
        with:
          action: close
