name: SWA Production (main)

on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - name: Build & Deploy to SWA (primary)
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_RIVER_008977F03 }}
          action: upload
          app_location: ./frontend
          api_location: ""
          output_location: dist
          # OBS: ingen deployment_environment här -> deployar till PRIMARY (Production)
